### ISSUE TITLE
Wasp units cannot be paralyzed in the original game

### ISSUE THREAD

**Issue by wandsmire** [Dzierzan/OpenSA#173] opened 2021-01-20 01:39 UTC
Wasp units cannot be paralyzed in the original game. 
Hopefully OpenRA engine supports this kind of behavior... 
Thank you.

**Comment by Dzierzan** [comment] 2021-01-20 08:08
Hi! Yes, they cannot be paralyzed in the original game. And they cannot be in OpenS either. Are you using the latest version? I just checked that and everything works as intended, that means Parasite units won't shoot each other and even if they got hit by Parasite's projectile, they won't be paralyzed.

**Comment by wandsmire** [comment] 2021-01-20 09:06
Not only the "parasite" unit, but also Assault and Sonic cannot be paralysed in the original game. CMIIW, I don't have the original game right now, but that just the way I remember it... I am using the latest build. thank you.

**Comment by Dzierzan** [comment] 2021-01-20 09:13
As I stated this, OpenSA is not a 1:1 recreation, but more like a remake. That means not everything is true to the original. Assault or Sonic units being able to be paralyzed is my intentional action, so Wasps vs Wasps has more sense. You'll find more similar stuff in this project. Either way, I am closing this as it's not the issue.

**Closed by Dzierzan** 2021-01-20 09:13 UTC
